name: togetherforever
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - conda-forge::biopython=1.72
  - bioconda::gffread=0.9.12-0
  - bioconda::openms=2.4.0-0
  - bioconda::msgf_plus=2017.07.21
  - conda-forge::r-data.table=1.11.4
  - conda-forge::r-hexbin=1.27.2
  - conda-forge::r-openxlsx=4.1.0
  - conda-forge::r-ggplot2=3.0.0
  - conda-forge::r-dplyr=0.7.6
  - conda-forge::r-devtools=1.13.6
  - conda-forge::r-domc=1.3.5
  - conda-forge::r-gridextra=2.3
  - conda-forge::r-ggthemes=4.0.1
  - conda-forge::r-scales=1.0.0
  - conda-forge::r-stringr=1.3.1
  - conda-forge::r-caret=6.0
  - conda-forge::r-kernlab=0.9
  - conda-forge::r-corrplot=0.84
  - conda-forge::r-lsr=0.5
  - conda-forge::r-plyr=1.8.4
  - conda-forge::r-shiny=1.2.0
  - conda-forge::r-ggrepel=0.8.0
  - bioconda::bioconductor-biocinstaller=1.32.1
