name: togetherforever
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - conda-forge::biopython=1.72
  - bioconda::gffread=0.9.12-0
  - bioconda::openms=2.3.0-0
  - bioconda::msgf_plus=2017.07.21
  - bioconda::percolator=3.1-0
